services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '${HTTP_PORT:-8000}:80'
      - '${SSL_PORT:-443}:443'
    environment:
      - SSL_PORT=${SSL_PORT:-443}
      - APP_SERVICE=${APP_SERVICE:-laravel.test}
      - SERVER_NAME=${SERVER_NAME:-localhost}
      - SSL_DOMAIN=${SSL_DOMAIN:-localhost}
      - SSL_ALT_NAME=${SSL_ALT_NAME:-DNS:localhost}
    volumes:
      - 'sail-nginx:/etc/nginx/certs'
      - './vendor/ryoluo/sail-ssl/nginx/templates:/etc/nginx/templates'
      - './vendor/ryoluo/sail-ssl/nginx/generate-ssl-cert.sh:/docker-entrypoint.d/99-generate-ssl-cert.sh'
      - './nginx-cert/local.mikatan-knitting.com+2-key.pem:/etc/certs/local.mikatan-knitting.com+2-key.pem'
      - './nginx-cert/local.mikatan-knitting.com+2.pem:/etc/certs/local.mikatan-knitting.com+2.pem'
    depends_on:
      - ${APP_SERVICE:-laravel.test}
    networks:
      - sail
  mikatan-laravel:
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      - './docker/8.3/my.cnf:/etc/my.cnf'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi
    ports:
      - '8010:8080'
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /openapi/openapi.yaml'
    volumes:
      - ./openapi:/openapi
    ports:
      - '8011:4010'
networks:
  sail:
    driver: bridge
volumes:
  sail-nginx:
    driver: local
  sail-mysql:
    driver: local
